// Blidworth Welfare FC — shared site data

const BW_DATA = {
  club: {
    name: 'Blidworth Welfare Football Club',
    short: 'Blidworth Welfare FC',
    nickname: 'The Welfare',
    founded: 1926,
    ground: 'Welfare Ground',
    location: 'Blidworth, Nottinghamshire',
    league: 'Camper UK League',
    division: 'Premier Division South',
    season: '2025/26',
    manager: 'Dan Mellors',
    captain: 'Tom Hodgkinson',
    colours: 'Black & White',
  },
  nextMatch: {
    home: { short: 'BWFC', name: 'Blidworth Welfare', crest: 'assets/crest.png' },
    away: { short: 'BOR', name: 'Borrowash Victoria' },
    comp: 'Camper UK Premier South',
    kickoff: '2026-04-21T19:45:00+01:00',
    venue: 'Welfare Ground',
    round: 'League',
    tickets: true,
  },
  lastMatch: {
    home: { short: 'BWFC', name: 'Blidworth Welfare', score: 1 },
    away: { short: 'HOL', name: 'Holbrook Sports', score: 2 },
    comp: 'Camper UK Premier South',
    date: '2026-04-18',
    scorers: [],
  },
  fixtures: [
    { date: '2026-04-21', time: '19:45', home: 'Blidworth Welfare', away: 'Borrowash Victoria',         comp: 'League',     venue: 'H' },
    { date: '2026-04-25', time: '15:00', home: 'Wirksworth Ivanhoe', away: 'Blidworth Welfare',         comp: 'League',     venue: 'A' },
    { date: '2026-04-28', time: '19:45', home: 'Blidworth Welfare', away: 'Linby Colliery Welfare',     comp: 'League',     venue: 'H' },
    { date: '2026-04-30', time: '19:45', home: 'Blidworth Welfare', away: 'Wirksworth Ivanhoe',         comp: 'League',     venue: 'H' },
    { date: '2026-05-02', time: '15:00', home: 'Cromford & Wirksworth Town', away: 'Blidworth Welfare', comp: 'League',     venue: 'A' },
  ],
  results: [
    { date: '2026-04-18', home: 'Blidworth Welfare',   hs: 1, away: 'Holbrook Sports',    as: 2, comp: 'League', ht: '1-1' },
    { date: '2026-04-18', home: 'Bakewell Town',       hs: 1, away: 'Borrowash Victoria', as: 2, comp: 'League' },
    { date: '2026-04-18', home: 'Cromford & Wirksworth Town', hs: 2, away: 'Graham Street Prims', as: 2, comp: 'League' },
    { date: '2026-04-18', home: 'Holbrook St Michaels', hs: 1, away: 'Melbourne Dynamo',  as: 1, comp: 'League' },
    { date: '2026-04-18', home: 'Selston F.C.',        hs: null, away: 'FC Sunnyhill',    as: null, comp: 'League', status: 'P-P' },
    { date: '2026-04-11', home: 'FC Sunnyhill',        hs: 2, away: 'Blidworth Welfare',  as: 0, comp: 'League' },
    { date: '2026-04-04', home: 'Blidworth Welfare',   hs: 1, away: 'Mickleover Athletic', as: 1, comp: 'League' },
    { date: '2026-03-28', home: 'Holbrook St Michaels', hs: 3, away: 'Blidworth Welfare', as: 1, comp: 'League' },
    { date: '2026-03-21', home: 'Blidworth Welfare',   hs: 2, away: 'Bakewell Town',      as: 2, comp: 'League' },
    { date: '2026-03-14', home: 'Graham Street Prims', hs: 4, away: 'Blidworth Welfare',  as: 0, comp: 'League' },
    { date: '2026-03-07', home: 'Blidworth Welfare',   hs: 1, away: 'Melbourne Dynamo',   as: 3, comp: 'League' },
  ],
  table: [
    { pos: 1, team: 'Graham Street Prims', p: 28, w: 20, d: 3, l: 5, gd: 24, pts: 63 },
    { pos: 2, team: 'Selston F.C. First', p: 27, w: 20, d: 2, l: 5, gd: 31, pts: 62 },
    { pos: 3, team: 'Borrowash Victoria First', p: 24, w: 16, d: 1, l: 7, gd: 28, pts: 49 },
    { pos: 4, team: 'Wirksworth Ivanhoe', p: 24, w: 15, d: 3, l: 6, gd: 20, pts: 48 },
    { pos: 5, team: 'Melbourne Dynamo', p: 26, w: 14, d: 5, l: 7, gd: 41, pts: 47 },
    { pos: 6, team: 'Holbrook Sports FC', p: 28, w: 13, d: 6, l: 9, gd: 3, pts: 45 },
    { pos: 7, team: 'Derby Singh Brothers', p: 24, w: 13, d: 3, l: 8, gd: 20, pts: 42 },
    { pos: 8, team: 'FC Sunnyhill', p: 27, w: 13, d: 3, l: 11, gd: 13, pts: 42 },
    { pos: 9, team: 'Mickleover R B L', p: 26, w: 12, d: 3, l: 11, gd: 11, pts: 39 },
    { pos: 10, team: 'Gresley Rovers Reserves', p: 28, w: 10, d: 5, l: 13, gd: 2, pts: 35 },
    { pos: 11, team: 'Linby Colliery Welfare F.C.', p: 26, w: 9, d: 5, l: 12, gd: -1, pts: 32 },
    { pos: 12, team: 'Holbrook St Michaels', p: 26, w: 9, d: 2, l: 15, gd: 0, pts: 29 },
    { pos: 13, team: 'Mickleover Athletic', p: 28, w: 8, d: 3, l: 17, gd: -13, pts: 27 },
    { pos: 14, team: 'Cromford & Wirksworth Town FC', p: 26, w: 6, d: 9, l: 11, gd: -18, pts: 27 },
    { pos: 15, team: 'Bakewell Town', p: 24, w: 6, d: 6, l: 12, gd: -12, pts: 24 },
    { pos: 16, team: 'Blidworth Welfare', p: 26, w: 5, d: 7, l: 14, gd: -38, pts: 22, self: true },
    { pos: 17, team: 'Mickleover Reserves', p: 30, w: 1, d: 2, l: 27, gd: -111, pts: 4 },
    { pos: 18, team: 'Mansfield Hosiery Mills F.C.', p: 0, w: 0, d: 0, l: 0, gd: 0, pts: 0 },
  ],
  news: [
    { id: 'four-to-play', cat: 'Call to Arms', title: 'Four games. One hundred years. Show up.', kicker: 'Sixteenth in the table, four fixtures left, three at the Welfare. A plea for everyone in the village to pack out the bank.', date: '2026-04-19', author: 'Club Media', img: 'terrace' },
    { id: 'holbrook-defeat', cat: 'Match Report', title: 'Welfare edged out 2-1 by Holbrook in front of biggest spring gate', kicker: 'A spirited showing not enough as Blidworth fall to a narrow home defeat with the drop now four points away.', date: '2026-04-18', author: 'Club Media', img: 'matchday' },
    { id: 'sunnyhill-defeat', cat: 'Match Report', title: 'Welfare fall to Sunnyhill as relegation gap narrows', kicker: 'Two first-half goals proved decisive as The Welfare failed to register a shot on target.', date: '2026-04-11', author: 'Club Media', img: 'matchday' },
    { id: 'centenary-launch', cat: 'Club', title: '100 Years: Centenary season programme unveiled', kicker: 'A year-long celebration of Welfare football — heritage kit, dinner, and a commemorative matchday at the Welfare Ground.', date: '2026-04-09', author: 'Club Media', img: 'archive' },
    { id: 'run-in-message', cat: 'First Team', title: '‘Six games, six finals’ — manager’s message ahead of the run-in', kicker: 'The gaffer calls on supporters to pack out the Welfare as the side look to finish the season strongly.', date: '2026-04-07', author: 'Club Media', img: 'manager' },
    { id: 'academy-intake', cat: 'Community', title: 'Academy opens 2026 summer intake applications', kicker: 'U9 to U16 trials confirmed across four weekends from June.', date: '2026-04-05', author: 'Academy', img: 'academy' },
    { id: 'new-kit', cat: 'Shop', title: 'Centenary home shirt — available to pre-order', kicker: 'Heritage black with gold trim, commemorating 100 years at the Welfare Ground.', date: '2026-04-02', author: 'Club Shop', img: 'kit' },
    { id: 'volunteer-day', cat: 'Community', title: 'Volunteer day: help us spruce up the ground', kicker: 'Paint, planting, and pitch-side improvements ahead of the centenary fixture.', date: '2026-03-30', author: 'Community', img: 'ground' },
  ],
  squad: [
    { no: 1, name: 'Aaron Finch', pos: 'GK', age: 29, apps: 28, goals: 0 },
    { no: 2, name: 'Will Barrett', pos: 'DF', age: 24, apps: 30, goals: 2 },
    { no: 3, name: 'Lewis Crampton', pos: 'DF', age: 26, apps: 27, goals: 1 },
    { no: 4, name: 'Tom Hodgkinson', pos: 'DF', age: 31, apps: 31, goals: 4, captain: true },
    { no: 5, name: 'Sam Oldfield', pos: 'DF', age: 23, apps: 25, goals: 3 },
    { no: 6, name: 'Kai Rutherford', pos: 'MF', age: 22, apps: 29, goals: 5 },
    { no: 7, name: 'Joe Whitlock', pos: 'FW', age: 25, apps: 30, goals: 18, topScorer: true },
    { no: 8, name: 'Callum Parr', pos: 'MF', age: 28, apps: 28, goals: 9 },
    { no: 9, name: 'Reece Mallinder', pos: 'FW', age: 26, apps: 26, goals: 14 },
    { no: 10, name: 'Harvey Stone', pos: 'MF', age: 21, apps: 24, goals: 7 },
    { no: 11, name: 'Leo Daventry', pos: 'FW', age: 20, apps: 22, goals: 6 },
    { no: 12, name: 'Miles Redfern', pos: 'GK', age: 34, apps: 4, goals: 0 },
    { no: 14, name: 'Ollie Ashworth', pos: 'MF', age: 23, apps: 20, goals: 2 },
    { no: 15, name: 'Ben Thackray', pos: 'DF', age: 27, apps: 19, goals: 0 },
    { no: 16, name: 'Jonah Kellett', pos: 'MF', age: 24, apps: 21, goals: 3 },
    { no: 17, name: 'Archie Denton', pos: 'FW', age: 19, apps: 15, goals: 4 },
    { no: 18, name: 'Isaac Pembrook', pos: 'DF', age: 22, apps: 14, goals: 0 },
    { no: 19, name: 'Finn Coppen', pos: 'MF', age: 20, apps: 12, goals: 1 },
  ],
  sponsors: [
    'BiFoldingDoors4U',
    'Mansfield Electricals',
    'Redvik',
    'TIS Bourne Ltd',
    'RCMC Projects',
    'The Forest Fox Pub',
    'NG21 Autocentre',
    'Welbeck Timber',
  ],
  socials: [
    { platform: 'X', handle: '@BlidworthWFC', when: '2h', text: 'TICKETS ⚡️ A limited allocation for Saturday’s home derby vs Ashfield Town goes on general sale at 10am. #UpTheWelfare' },
    { platform: 'Instagram', handle: '@blidworth_welfare_fc', when: '8h', text: 'Matchday eve. Final session in the books. We go again Saturday. 🖤🤍' },
    { platform: 'Facebook', handle: 'Blidworth Welfare FC', when: '1d', text: 'Huge thanks to everyone who came down for the volunteer day — the Welfare Ground is looking the business ahead of the centenary fixture.' },
    { platform: 'X', handle: '@BlidworthWFC', when: '2d', text: 'FT | Blidworth Welfare 3-1 Rainworth MW. Derby day delivered. Whitlock (2), Parr. Four points off top spot. #UpTheWelfare' },
  ],
  honours: [
    { year: '2023/24', title: 'CMA South Division — Champions' },
    { year: '2018/19', title: 'Notts Senior League — Runners-up' },
    { year: '2012/13', title: 'Notts Senior Cup — Winners' },
    { year: '1998/99', title: 'Central Alliance — Champions' },
    { year: '1978/79', title: 'Notts Spartan League — Winners' },
  ],
};

window.BW_DATA = BW_DATA;
